version: '3.0'
services:
  mysql8:
    image: mysql:8.0.29
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "13306:3306"
    volumes:
      # 将当前目录下的./scripts/mysql/文件夹映射到Docker容器的/docker-entrypoint-initdb.d/目录下，
      # 使得在该文件夹中存放的SQL脚本能在MySQL容器启动时自动执行
      - ./scripts/mysql/:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=root
#  redis:
#    image: bitnami/redis:latest
#    environment:
#      - ALLOW_EMPTY_PASSWORD=yes
#    ports:
#      - "6379:6379"