apiVersion: v1
kind: PersistentVolume
metadata:
  name: webook-mysql-pv
  labels:
    app: webook-mysql-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/tmp/data/mysql"