apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webook-mysql-pvc
  labels:
    app: webook-mysql-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  