---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zq.
--- DateTime: 2023/12/1 15:38
---

wrk.method="POST"
wrk.headers["Content-Type"] = "application/json"
-- 修改自己的login信息
wrk.body='{"email":"12345@qq.com", "password": "hello@world123"}'