---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zq.
--- DateTime: 2023/12/1 15:37
---
wrk.method="GET"
wrk.headers["Content-Type"] = "application/json"
--wrk.headers["User-Agent"] = "PostmanRuntime/7.32.3"
-- 修改为自己的token
wrk.headers["Authorization"]="Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDE1MDY5ODgsIlVpZCI6MiwiVXNlckFnZW50IjoiIn0.MP4eiO77cBWBp-1m38j4rGbQVp2kf-V2sapRo4dEOjJ6v77HWYQwGlw1uLbLxvOoYsJlBY7lLsrTEjxSodWqHQ"
