db:
  src:
    dsn: "root:root@tcp(localhost:13306)/webook"
  dst:
    dsn: "root:root@tcp(localhost:13306)/webook_intr"

migrator:
  pattern: "SRC_ONLY"
  web:
    add: ":8082"

redis:
  addr: "localhost:6379"

kafka:
  addrs:
    - "localhost:9094"

grpc:
  server:
    addr: ":8090"