db:
  dsn: "root:root@tcp(localhost:13306)/webook?charset=utf8mb4&parseTime=True&loc=Local"

redis:
  addr: "localhost:6379"

etcd:
  endpoints:
    - "localhost:12378"

kafka:
  addrs:
    - "localhost:9094"

grpc:
  client:
    intr:
      name: "interactive"
      secure: false
      threshold: 100
